name: ironfit
description: "A new Flutter project focused on a Coach Dashboard with card-based navigation."
publish_to: 'none' # Keeps the package private

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.0.1
  # State management using GetX for dashboard logic and navigation
  get: ^4.6.5

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0

  # Add any other packages your project might need like HTTP for API calls
  # Example:
  # http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Declare assets for coach photos and icons if applicable
  assets:
    - assets/images/gym.jpg
    - assets/images/trainer.jpg
    - assets/images/signOne.jpeg
    - assets/images/IronFit.png
    - assets/images/preLogin1.jpg
    - assets/images/preLogin2.png
    - assets/images/preLogin3.png
    - assets/images/header.png
    - assets/images/IronFitLogo2.png
    - assets/images/dashboardBackground.jpg
    - assets/images/dashboardYellow.png
    - assets/images/myGymImage.png
    - assets/images/placeholder.svg

  # Fonts can also be added if required for custom typography
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf

flutter_native_splash:
  color: "#ffbb02"  # Background color
  image: assets\images\IronFitLogo2.png  # Logo or image you want to display
  android: true  # Enable splash screen for Android
  ios: true  # Enable splash screen for iOS
  

