name: ironfit
description: "A new Flutter project focused on a Coach Dashboard with card-based navigation."
publish_to: 'none' # Keeps the package private

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.0.1

  # State management using GetX for dashboard logic and navigation
  get: ^4.6.5

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.6

  # Add any other packages your project might need like HTTP for API calls
  # Example:
  # http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Declare assets for coach photos and icons if applicable
  assets:
    - assets/images/gym.jpg
    - assets/images/trainer.jpg
    - assets/images/signOne.jpeg
    - assets/images/IronFit.png
    - assets/images/preLogin1.jpg
    - assets/images/preLogin2.png
    - assets/images/preLogin3.png
    - assets/images/header.png

  # Fonts can also be added if required for custom typography
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
