name: ironfit
description: "A new Flutter project focused on a Coach Dashboard with card-based navigation."
publish_to: 'none' # Keeps the package private

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  percent_indicator: ^4.0.1
  # State management using GetX for dashboard logic and navigation
  get: ^4.6.5

  # Cupertino Icons for iOS style icons
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  firebase_storage: ^12.3.3
  image_picker: ^1.1.2
  carousel_slider: ^5.0.0
  dropdown_search: ^6.0.1
  flutter_launcher_icons: ^0.14.1
  firebase_app_check: ^0.3.1+4
  flutter_local_notifications: ^17.2.3
  firebase_messaging: ^15.1.3
  timezone: ^0.9.4
  workmanager: ^0.5.2
  google_fonts: ^6.2.1

  # Add any other packages your project might need like HTTP for API calls
  # Example:
  # http: ^0.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Declare assets for coach photos and icons if applicable
  assets:
    - assets/images/gym.jpg
    - assets/images/trainer.jpg
    - assets/images/signOne.jpeg
    - assets/images/IronFit.png
    - assets/images/preLogin1.jpg
    - assets/images/preLogin2.png
    - assets/images/preLogin3.png
    - assets/images/header.png
    - assets/images/IronFitLogo2.png
    - assets/images/dashboardBackground.jpg
    - assets/images/dashboardYellow.png
    - assets/images/myGymImage.png
    - assets/images/placeholder.svg
    - assets/images/google-logo.png
    - assets/images/Welcome-to.png
    - assets/images/selectLangBackground.png
    - assets/images/logo.png
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/exresices/back_exercises.json
    - assets/exresices/cardio_exercises.json
    - assets/exresices/chest_exercises.json
    - assets/exresices/lower arms_exercises.json
    - assets/exresices/lower legs_exercises.json
    - assets/exresices/neck_exercises.json
    - assets/exresices/shoulders_exercises.json
    - assets/exresices/upper arms_exercises.json
    - assets/exresices/upper legs_exercises.json
    - assets/exresices/waist_exercises.json

  # Fonts can also be added if required for custom typography
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf

flutter_native_splash:
  color: "#ffbb02"  # Background color
  image: assets/images/Welcome-to.png  # Logo or image you want to display
  android: true  # Enable splash screen for Android
  ios: true  # Enable splash screen for iOS

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: "launcher_icon"
  image_path_android: "assets/images/logo.png"
  min_sdk_android: 23 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo.png"
  # adaptive_icon_monochrome: "assets/icon/monochrome.png"

  ios: true
  image_path_ios: "assets/images/logo.png"
  remove_alpha_channel_ios: true
  # image_path_ios_dark_transparent: "assets/icon/icon_dark.png"
  # image_path_ios_tinted_grayscale: "assets/icon/icon_tinted.png"
  # desaturate_tinted_to_grayscale_ios: true

  web:
    generate: true
    image_path: "assets/images/logo.png"

  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/images/logo.png"

