# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'Runner' do
  pod 'Firebase/Core', '~> 10.0' # Adjust the version as per your dependency
  pod 'Firebase/Auth', '~> 10.0'
  pod 'Firebase/Firestore', '~> 10.0'
  pod 'Firebase/Storage', '~> 10.0'
  pod 'Firebase/Analytics', '~> 10.0'
  pod 'Firebase/Messaging', '~> 10.0'
  pod 'GoogleSignIn', '~> 6.0'
  pod 'FlutterNativeSplash', '~> 2.4.1'
  pod 'ImagePicker', '~> 0.8.6' # Adjust the version as per your dependency
  pod 'FlutterLocalNotifications', '~> 17.0'
  pod 'WorkManager', '~> 0.5.2'
  pod 'CarouselSlider', '~> 5.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
